services:
  #-------------------
  # Backend Service
  #-------------------
  - type: web
    name: codebase-copilot-backend
    runtime: docker
    dockerfilePath: ./backend.Dockerfile
    healthCheck:
      path: /
      initialDelaySeconds: 60
    disks:
      - name: sessions
        mountPath: /app/sessions
        sizeGB: 1
      - name: sessions-code
        mountPath: /app/sessions_code
        sizeGB: 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11

  #-------------------
  # Frontend Service
  #-------------------
  - type: web
    name: codebase-copilot-frontend
    runtime: docker
    dockerfilePath: ./frontend.Dockerfile 
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: STREAMLIT_BACKEND_URL
        value: http://codebase-copilot-backend:8000/api