services:
  #-------------------
  # Backend Service
  #-------------------
  - type: web
    name: codebase-copilot-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    healthCheck:
      path: /
      initialDelaySeconds: 60
    # Persistent disks to store session data across deploys
    disks:
      - name: sessions
        mountPath: /app/sessions
        sizeGB: 1
      - name: sessions-code
        mountPath: /app/sessions_code
        sizeGB: 2
    # Environment variables will be set in the Render UI
    # See deployment guide below
    envVars:
      - key: PYTHON_VERSION
        value: 3.11

  #-------------------
  # Frontend Service
  #-------------------
  - type: web
    name: codebase-copilot-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      # IMPORTANT: This tells the frontend how to communicate with the backend
      # using Render's internal service discovery.
      - key: STREAMLIT_BACKEND_URL
        value: http://codebase-copilot-backend:8000/api